name = "LessUnitful"
uuid = "f29f6376-6e90-4d80-80c9-fb8ec61203d5"
authors = ["Jürgen Fuhrmann <juergen-fuhrmann@web.de>"]
version = "0.0.1"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.6"
Unitful = "1.11"
PhysicalConstants = "0.2"
