name = "LessUnitful"
uuid = "f29f6376-6e90-4d80-80c9-fb8ec61203d5"
authors = ["Jürgen Fuhrmann <juergen-fuhrmann@web.de>"]
version = "1.0.1"

[deps]
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
PhysicalConstants = "0.2"
Unitful = "1.11"
julia = "1.6"
